const roomsSectionsDefault = {
  content: [
    {
      label: 'Recommended rooms',
      elements: [
        { iconLeft: 'globe.svg', name: 'Room name', online: 0, iconRight: 'profile_darker.svg' },
        { iconLeft: 'globe.svg', name: 'Room #1', online: 0, iconRight: 'profile_darker.svg' },
        { iconLeft: 'globe.svg', name: 'Room #2', online: 0, iconRight: 'profile_darker.svg' },
        { iconLeft: 'globe.svg', name: 'Room #3', online: 0, iconRight: 'profile_darker.svg' },
        { iconLeft: 'globe.svg', name: 'Room #4', online: 0, iconRight: 'profile_darker.svg' },
        { iconLeft: 'globe.svg', name: 'Room #5', online: 0, iconRight: 'profile_darker.svg' },
        { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg' },
      ],
    },
    {
      label: 'All rooms',
      elements: [
        { iconLeft: 'globe.svg', name: 'Room #1', online: 0, iconRight: 'profile_darker.svg', selected: true },
        { iconLeft: 'globe.svg', name: 'Room #2', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #3', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #4', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #5', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #7', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #8', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #10', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #11', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #12', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #13', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #14', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #15', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #16', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #17', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #18', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #19', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #20', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #21', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #22', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #22', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #23', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #24', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #25', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #26', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #27', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #28', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #29', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #30', online: 0, iconRight: 'profile_darker.svg', selected: false },
        { iconLeft: 'globe.svg', name: 'Room #31', online: 0, iconRight: 'profile_darker.svg', selected: false },
      ],
    },
  ],
  footer: 'Users online',
};

const usersSectionsDefault = {
  content: [
    {
      label: `Online (${7})`,
      elements: [
        { iconLeft: 'profile_darker.svg', name: 'Room name' },
        { iconLeft: 'profile_darker.svg', name: 'Room #1' },
        { iconLeft: 'profile_darker.svg', name: 'Room #2' },
        { iconLeft: 'profile_darker.svg', name: 'Room #3' },
        { iconLeft: 'profile_darker.svg', name: 'Room #4' },
        { iconLeft: 'profile_darker.svg', name: 'Room #5' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
        { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      ],
    },
  ],
  footer: 'Rooms',
};

export { roomsSectionsDefault, usersSectionsDefault };
