const roomsSectionsDefault = {
  content: [
    {
      label: 'Recommended rooms',
      maxHeight: '30vh',
      elements: [
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room name',
          textRight: '0',
          iconRight: 'profile_darker.svg',
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #1',
          textRight: '0',
          iconRight: 'profile_darker.svg',
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #2',
          textRight: '0',
          iconRight: 'profile_darker.svg',
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #3',
          textRight: '0',
          iconRight: 'profile_darker.svg',
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #4',
          textRight: '0',
          iconRight: 'profile_darker.svg',
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #5',
          textRight: '0',
          iconRight: 'profile_darker.svg',
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #6',
          textRight: '0',
          iconRight: 'profile_darker.svg',
        },
      ],
    },
    {
      label: 'All rooms',
      elements: [
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #1',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: true,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #2',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #3',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #4',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #5',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #6',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #7',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #8',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #9',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #10',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #11',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #12',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #13',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #14',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #15',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #16',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #17',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #18',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #19',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #20',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #21',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #22',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #22',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #23',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #24',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #25',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #26',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #27',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #28',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #29',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #30',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
        {
          iconLeft: 'globe.svg',
          textLeft: 'Room #31',
          textRight: '0',
          iconRight: 'profile_darker.svg',
          selected: false,
        },
      ],
    },
  ],
  footer: 'Users online',
};

const usersSectionsDefault = {
  content: [
    {
      label: `textRight (${7})`,
      elements: [
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room textLeft',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #1',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #2',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #3',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #4',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #5',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
        {
          iconLeft: 'profile_darker.svg',
          textLeft: 'Room #6',
        },
      ],
    },
  ],
  footer: 'Rooms',
};

export { roomsSectionsDefault, usersSectionsDefault };
