const roomsSections = [
  {
    label: 'Recommended rooms',
    elements: [
      { iconLeft: 'globe.svg', name: 'Room name', online: 0, iconRight: 'profile_darker.svg', selected: true },
      { iconLeft: 'globe.svg', name: 'Room #1', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #2', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #3', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #4', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #5', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
    ],
  },
  {
    label: 'All rooms',
    elements: [
      { iconLeft: 'globe.svg', name: 'Room #1', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #2', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #3', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #4', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #5', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #6', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #7', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #8', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
      { iconLeft: 'globe.svg', name: 'Room #9', online: 0, iconRight: 'profile_darker.svg', selected: false },
    ],
  },
];

const usersSections = [
  {
    label: `Online (${7})`,
    elements: [
      { iconLeft: 'profile_darker.svg', name: 'Room name' },
      { iconLeft: 'profile_darker.svg', name: 'Room #1' },
      { iconLeft: 'profile_darker.svg', name: 'Room #2' },
      { iconLeft: 'profile_darker.svg', name: 'Room #3' },
      { iconLeft: 'profile_darker.svg', name: 'Room #4' },
      { iconLeft: 'profile_darker.svg', name: 'Room #5' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
      { iconLeft: 'profile_darker.svg', name: 'Room #6' },
    ],
  },
];

export { roomsSections, usersSections };
